plugins {
    id 'java-library'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['src', 'themes']
            exclude '**/*.java'
        }
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api fileTree(dir: 'dev_libs', include: ['*.jar'])
}
